'use strict';

export const RARITY_COLORS = {
  common:      '#94a3b8',
  uncommon:    '#22c55e',
  rare:        '#3b82f6',
  epic:        '#a855f7',
  legendary:   '#f59e0b',
  otherworldly:'#c084fc',
};

export const ARTIFACTS = [
  {
    id: 'lucky_paw',
    name: 'Lucky Paw',
    icon: '🐾',
    rarity: 'uncommon',
    desc: '+10% resource drop chance from enemies.',
    flavor: '"Fortune favors the persistent."',
    cost: 30,
  },
  {
    id: 'heralds_horn',
    name: "Herald's Horn",
    icon: '📯',
    rarity: 'rare',
    desc: 'Boss waves announced 1 wave early.',
    flavor: '"Blow it before the moment, not during."',
    cost: 0,
    pipShop: false,
  },
  {
    id: 'tally_stick',
    name: 'Tally Stick',
    icon: '🪵',
    rarity: 'uncommon',
    desc: '+15% chance of Dust drops from enemies.',
    flavor: '"The notches are older than the wood."',
    cost: 35,
    pipShop: false,
  },
  {
    id: 'warm_pebble',
    name: 'Warm Pebble',
    icon: '🪨',
    rarity: 'uncommon',
    desc: 'Towers adjacent to the Lab deal 10% more damage.',
    flavor: '"Where does the heat come from?"',
    cost: 40,
    pipShop: false,
  },
  {
    id: 'the_bell',
    name: 'The Bell',
    icon: '🔔',
    rarity: 'rare',
    desc: 'Active: Freeze all enemies for 2.5 seconds.',
    flavor: '"It\'s a pause."',
    cost: 0,
    active: true,
    cooldownWaves: 8,
    pipShop: false,
  },
  {
    id: 'auditors_ledger',
    name: "Auditor's Ledger",
    icon: '📒',
    rarity: 'legendary',
    desc: 'Reveals the composition of the next wave in the wave banner.',
    flavor: '"Every transaction, recorded."',
    cost: 0,
    unique: true,
    pipShop: false,
  },
  {
    id: 'unblinking_eye',
    name: 'The Unblinking Eye',
    icon: '👁️',
    rarity: 'otherworldly',
    desc: 'All towers gain +0.5 range while equipped.',
    flavor: '"It watches. It has always watched."',
    cost: 0,
    unique: true,
    pipShop: false,
  },
  {
    id: 'spider_staff',
    name: 'Spider Staff',
    icon: '🕸️',
    rarity: 'legendary',
    desc: 'Active: Click a path tile to cover 5 adjacent tiles with webs (60% slow, 3 dmg/tick). Lasts the whole wave. Once per wave.',
    flavor: '"She left it. A gesture, maybe. Or a warning."',
    cost: 0,
    unique: true,
    active: true,
    cooldownWaves: 1,
    pipShop: false,
  },
  {
    id: 'goblin_lullaby',
    name: 'Goblin Lullaby',
    icon: '🎵',
    rarity: 'common',
    desc: 'Enemies in the Lab\'s observation radius move 10% slower.',
    flavor: '"Old. Older than the castle."',
    cost: 25,
  },
  {
    id: 'chipped_mirror',
    name: 'Chipped Mirror',
    icon: '🪞',
    rarity: 'uncommon',
    desc: 'All towers adjacent to the Lab fire 10% faster.',
    flavor: '"One side reflects. The other doesn\'t."',
    cost: 40,
  },
];
